#设置端口号
server:
  port: 1081

#代理模式有 pac|global|direct三种
proxy:
  mode: pac

socks5:
  authentication:
    enabel: true
    #socks5认证信息文件，存储着用户名:密码键值对
    path: ./users.properties

trojan:
  password: 密码
  server:
    host: 服务器地址
    port: 443

#pac文件路径，0：直连；-1：拒绝连接；1：代理连接
pacfile:
  path: ./pac.txt
